// A stand-in for the Pebble SDK's pebble.h, declaring only what main.c
// uses, with the SDK's signatures, so the watch app can be type-checked
// where the SDK cannot be installed. It is not the SDK and links nothing.
#pragma once
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

typedef struct Window Window;
typedef struct Layer Layer;
typedef struct GContext GContext;
typedef struct GBitmap GBitmap;
typedef struct {int16_t x,y;} GPoint;
typedef struct {int16_t w,h;} GSize;
typedef struct {GPoint origin;GSize size;} GRect;
#define GRect(x,y,w,h) ((GRect){{(x),(y)},{(w),(h)}})
typedef union {uint8_t argb;} GColor8;
typedef GColor8 GColor;
#define GColorBlack ((GColor8){.argb=0xC0})
#define GColorWhite ((GColor8){.argb=0xFF})
typedef enum {GCornerNone=0} GCornerMask;
typedef enum {GTextOverflowModeWordWrap,GTextOverflowModeTrailingEllipsis,GTextOverflowModeFill} GTextOverflowMode;
typedef enum {GTextAlignmentLeft,GTextAlignmentCenter,GTextAlignmentRight} GTextAlignment;
typedef struct GTextAttributes GTextAttributes;
typedef struct GFontInfo *GFont;
#define FONT_KEY_GOTHIC_14 "RESOURCE_ID_GOTHIC_14"

typedef void (*WindowHandler)(Window *window);
typedef struct {WindowHandler load,appear,disappear,unload;} WindowHandlers;
Window *window_create(void);
void window_destroy(Window *window);
void window_set_window_handlers(Window *window,WindowHandlers handlers);
void window_stack_push(Window *window,bool animated);
Layer *window_get_root_layer(const Window *window);

typedef void (*LayerUpdateProc)(Layer *layer,GContext *ctx);
Layer *layer_create(GRect frame);
void layer_destroy(Layer *layer);
GRect layer_get_bounds(const Layer *layer);
void layer_set_update_proc(Layer *layer,LayerUpdateProc update_proc);
void layer_add_child(Layer *parent,Layer *child);
void layer_mark_dirty(Layer *layer);

GBitmap *graphics_capture_frame_buffer(GContext *ctx);
bool graphics_release_frame_buffer(GContext *ctx,GBitmap *buffer);
uint8_t *gbitmap_get_data(const GBitmap *bitmap);
uint16_t gbitmap_get_bytes_per_row(const GBitmap *bitmap);
void graphics_context_set_fill_color(GContext *ctx,GColor color);
void graphics_context_set_text_color(GContext *ctx,GColor color);
void graphics_fill_rect(GContext *ctx,GRect rect,uint16_t corner_radius,GCornerMask corner_mask);
void graphics_draw_text(GContext *ctx,const char *text,GFont font,GRect box,GTextOverflowMode overflow_mode,GTextAlignment alignment,GTextAttributes *text_attributes);
GFont fonts_get_system_font(const char *font_key);

typedef enum {SECOND_UNIT=1,MINUTE_UNIT=2,HOUR_UNIT=4,DAY_UNIT=8,MONTH_UNIT=16,YEAR_UNIT=32} TimeUnits;
typedef void (*TickHandler)(struct tm *tick_time,TimeUnits units_changed);
void tick_timer_service_subscribe(TimeUnits tick_units,TickHandler handler);
void tick_timer_service_unsubscribe(void);

typedef enum {APP_MSG_OK=0} AppMessageResult;
typedef enum {DICT_OK=0} DictionaryResult;
typedef struct DictionaryIterator DictionaryIterator;
typedef struct {
  uint32_t key;uint8_t type;uint16_t length;
  union {uint8_t data[0];char cstring[0];uint8_t uint8;uint16_t uint16;uint32_t uint32;int8_t int8;int16_t int16;int32_t int32;} value[];
} Tuple;
typedef void (*AppMessageInboxReceived)(DictionaryIterator *iterator,void *context);
typedef void (*AppMessageOutboxFailed)(DictionaryIterator *iterator,AppMessageResult reason,void *context);
AppMessageResult app_message_open(uint32_t size_inbound,uint32_t size_outbound);
uint32_t app_message_inbox_size_maximum(void);
AppMessageInboxReceived app_message_register_inbox_received(AppMessageInboxReceived received_callback);
AppMessageOutboxFailed app_message_register_outbox_failed(AppMessageOutboxFailed failed_callback);
AppMessageResult app_message_outbox_begin(DictionaryIterator **iterator);
AppMessageResult app_message_outbox_send(void);
Tuple *dict_find(const DictionaryIterator *iter,const uint32_t key);
DictionaryResult dict_write_int32(DictionaryIterator *iter,const uint32_t key,const int32_t value);
// Generated by the SDK from package.json's messageKeys.
extern uint32_t MESSAGE_KEY_Status,MESSAGE_KEY_Events,
  MESSAGE_KEY_Settings,MESSAGE_KEY_Segments,MESSAGE_KEY_RiseSets,MESSAGE_KEY_DataRequest,
  MESSAGE_KEY_DataBody,MESSAGE_KEY_SatSegments,MESSAGE_KEY_Passes;

typedef enum {APP_LOG_LEVEL_ERROR=1,APP_LOG_LEVEL_WARNING=50,APP_LOG_LEVEL_INFO=100,APP_LOG_LEVEL_DEBUG=200} AppLogLevel;
void app_log(uint8_t log_level,const char *src_filename,int src_line_number,const char *fmt,...);
#define APP_LOG(level,fmt,...) app_log(level,__FILE__,__LINE__,fmt,##__VA_ARGS__)
size_t heap_bytes_free(void);
uint16_t time_ms(time_t *tloc,uint16_t *out_ms);
typedef struct AppTimer AppTimer;
typedef void (*AppTimerCallback)(void *data);
AppTimer *app_timer_register(uint32_t timeout_ms,AppTimerCallback callback,void *callback_data);
bool app_timer_reschedule(AppTimer *timer_handle,uint32_t new_timeout_ms);
struct tm *localtime(const time_t *timep);
typedef void *ResHandle;
#define GColorClear ((GColor8){.argb=0x00})
void window_set_background_color(Window *window,GColor background_color);
typedef void (*AppFocusHandler)(bool in_focus);
void app_focus_service_subscribe(AppFocusHandler handler);
typedef struct {uint8_t charge_percent;bool is_charging,is_plugged;} BatteryChargeState;
typedef void (*BatteryStateHandler)(BatteryChargeState charge);
BatteryChargeState battery_state_service_peek(void);
void battery_state_service_subscribe(BatteryStateHandler handler);
void battery_state_service_unsubscribe(void);
typedef void (*ConnectionHandler)(bool connected);
typedef struct {ConnectionHandler pebble_app_connection_handler,pebkit_connection_handler;} ConnectionHandlers;
bool connection_service_peek_pebble_app_connection(void);
void connection_service_subscribe(ConnectionHandlers handlers);
void connection_service_unsubscribe(void);
void app_focus_service_unsubscribe(void);
ResHandle resource_get_handle(uint32_t resource_id);
size_t resource_size(ResHandle h);
size_t resource_load(ResHandle h,uint8_t *buffer,size_t max_length);
size_t resource_load_byte_range(ResHandle h,uint32_t start_offset,uint8_t *buffer,size_t num_bytes);
int persist_read_data(const uint32_t key,void *buffer,const size_t buffer_size);
int persist_write_data(const uint32_t key,const void *data,const size_t size);
int persist_delete(uint32_t key);
// Generated by the SDK from package.json's resources.
#define RESOURCE_ID_MAP_PACK 1
#define RESOURCE_ID_TABLES 3
#define RESOURCE_ID_FIGURES 2
#define RESOURCE_ID_FULLER_GRIDS 4
#define RESOURCE_ID_LAND_BITS 5
#define RESOURCE_ID_FONT 6
void app_event_loop(void);
