// Generated by tools/generate-native-font.mjs from data/departure-font.json.
// Departure Mono by Helena Zhang, SIL OFL 1.1.
#pragma once
#include <stdint.h>
typedef struct {uint8_t x,y,n;} EnrRun;
typedef struct {int8_t advance,left,top;uint16_t first,count;} EnrGlyph;
extern const char ENR_FONT_CHARS[40];
extern const EnrGlyph ENR_FONT_GLYPHS[39];
extern const EnrRun ENR_FONT_RUNS[437];
