// Bundle the phone side of the native app, native/pkjs/main.js with the
// ephemeris and orbit code it fits segments with, into
// native/src/pkjs/index.js for the Pebble SDK to package.
//
//   node tools/build-pkjs.mjs [out-file]
import {readFileSync,mkdirSync} from 'node:fs';
import {dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';

const root=new URL('..',import.meta.url);
const out=process.argv[2]||fileURLToPath(new URL('native/src/pkjs/index.js',root));

const data={
  name:'groundtrack-data',
  setup(b){
    // satellite.js's WebAssembly builds load only on request, which the
    // phone never makes; they need Node and would triple the bundle.
    b.onResolve({filter:/^#wasm-/},()=>({path:'wasm',namespace:'groundtrack'}));
    b.onLoad({filter:/^wasm$/,namespace:'groundtrack'},()=>({contents:'export default null;',loader:'js'}));
  }
};

mkdirSync(dirname(out),{recursive:true});
const result=await build({
  entryPoints:[fileURLToPath(new URL('native/pkjs/main.js',root))],
  // The SDK repackages this with webpack 1, whose parser takes ES2015 at most
  // and which indents every line of the file: a template literal spanning
  // lines would gain tabs, so none are emitted and every newline stays '\n'.
  bundle:true,format:'iife',platform:'browser',target:'es2015',supported:{'template-literal':false},minify:true,legalComments:'eof',
  banner:{js:'// Generated by tools/build-pkjs.mjs from native/pkjs/main.js. Do not edit.'},
  loader:{'.html':'text'},plugins:[data],outfile:out,metafile:true,logLevel:'warning'
});
const bytes=Object.values(result.metafile.outputs)[0].bytes;
console.log(`${out}: ${(bytes/1024).toFixed(0)} KB`);
