// Bundle the phone side of the native app: native/pkjs/main.js with the
// renderer, and the coastline atlas and relief grid deflated and embedded
// as base64, into native/src/pkjs/index.js for the Pebble SDK to package.
// The repository is private, so the phone can't fetch the data from it.
//
//   node tools/build-pkjs.mjs [out-file]
import {readFileSync,mkdirSync} from 'node:fs';
import {dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import {deflateSync} from 'fflate';

const root=new URL('..',import.meta.url);
const out=process.argv[2]||fileURLToPath(new URL('native/src/pkjs/index.js',root));
const packed=name=>Buffer.from(deflateSync(readFileSync(new URL(`public/${name}`,root)),{level:9})).toString('base64');

const data={
  name:'groundtrack-data',
  setup(b){
    b.onResolve({filter:/^groundtrack:data$/},()=>({path:'data',namespace:'groundtrack'}));
    // satellite.js's WebAssembly builds load only on request, which the
    // renderer never makes; they need Node and would triple the bundle.
    b.onResolve({filter:/^#wasm-/},()=>({path:'wasm',namespace:'groundtrack'}));
    b.onLoad({filter:/^wasm$/,namespace:'groundtrack'},()=>({contents:'export default null;',loader:'js'}));
    b.onLoad({filter:/^data$/,namespace:'groundtrack'},()=>({contents:`export const LAND=${JSON.stringify(packed('land.bin'))};\nexport const RELIEF=${JSON.stringify(packed('relief.bin'))};\n`,loader:'js'}));
  }
};

mkdirSync(dirname(out),{recursive:true});
const result=await build({
  entryPoints:[fileURLToPath(new URL('native/pkjs/main.js',root))],
  // The SDK repackages this with webpack 1, whose parser takes ES2015 at most
  // and which indents every line of the file: a template literal spanning
  // lines would gain tabs, so none are emitted and every newline stays '\n'.
  bundle:true,format:'iife',platform:'browser',target:'es2015',supported:{'template-literal':false},minify:true,legalComments:'eof',
  banner:{js:'// Generated by tools/build-pkjs.mjs from native/pkjs/main.js. Do not edit.'},
  plugins:[data],outfile:out,metafile:true,logLevel:'warning'
});
const bytes=Object.values(result.metafile.outputs)[0].bytes;
console.log(`${out}: ${(bytes/1024).toFixed(0)} KB`);
