// Bundle the phone side of the native app, native/pkjs/main.js with the
// ephemeris and orbit code it fits segments with, into
// native/src/pkjs/index.js for the Pebble SDK to package; with --face
// fuller, Groundtrack Fuller's into native-fuller/src/pkjs/index.js.
//
//   node tools/build-pkjs.mjs [--face enroute|fuller] [out-file]
import {readFileSync,mkdirSync} from 'node:fs';
import {gzipSync} from 'node:zlib';
import {dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';

const root=new URL('..',import.meta.url);
const args=process.argv.slice(2),at=args.indexOf('--face'),face=at>=0?args.splice(at,2)[1]:'enroute';
if(!['enroute','fuller'].includes(face))throw new Error(`No face ${face}`);
const out=args[0]||fileURLToPath(new URL(face==='enroute'?'native/src/pkjs/index.js':`native-${face}/src/pkjs/index.js`,root));

const data={
  name:'groundtrack-data',
  setup(b){
    // satellite.js's WebAssembly builds load only on request, which the
    // phone never makes; they need Node and would triple the bundle.
    b.onResolve({filter:/^#wasm-/},()=>({path:'wasm',namespace:'groundtrack'}));
    b.onLoad({filter:/^wasm$/,namespace:'groundtrack'},()=>({contents:'export default null;',loader:'js'}));
  }
};

// The settings page's preview runs the watch's own core (public/core.wasm,
// tools/build-core.sh) on the face's resources, from chart inputs it makes
// itself (src/page-input.js, a script of its own): one gzip of them all, in
// base64, with each part's kind (core_api.h's CORE_MAP ... CORE_LAND; -1
// the core, -2 the script) and place.
const PARTS={enroute:[[-1,'public/core.wasm'],[0,'native/resources/map.pack'],[1,'native/resources/figures.bin'],[2,'native/resources/tables.bin']],
  fuller:[[-1,'public/core.wasm'],[3,'public/fuller.bin'],[4,'native/resources/land.pack'],[1,'native/resources/figures.bin'],[2,'native/resources/tables.bin']]}[face];
const pageAssets={
  name:'groundtrack-page-assets',
  setup(b){
    b.onResolve({filter:/^groundtrack-page-assets$/},()=>({path:'page-assets',namespace:'groundtrack'}));
    b.onLoad({filter:/^page-assets$/,namespace:'groundtrack'},async()=>{
      const script=await build({entryPoints:[fileURLToPath(new URL('src/page-input.js',root))],bundle:true,format:'iife',globalName:'GroundtrackInput',platform:'browser',target:'es2015',minify:true,legalComments:'none',plugins:[data],write:false,logLevel:'warning'});
      const kinds=[...PARTS.map(p=>p[0]),-2],files=[...PARTS.map(([,f])=>readFileSync(fileURLToPath(new URL(f,root)))),Buffer.from(script.outputFiles[0].contents)],parts=[];let at=0;
      for(let k=0;k<files.length;k++){parts.push([kinds[k],at,files[k].length]);at+=files[k].length;}
      return {contents:`export default ${JSON.stringify({gz:gzipSync(Buffer.concat(files),{level:9}).toString('base64'),parts})};`,loader:'js'};
    });
  }
};

// The settings page takes the same rules as the phone and the tests
// (src/settings-rules.js), as text for its own script.
const rulesText={
  name:'groundtrack-rules-text',
  setup(b){
    b.onResolve({filter:/^groundtrack-rules-text$/},()=>({path:'rules-text',namespace:'groundtrack'}));
    b.onLoad({filter:/^rules-text$/,namespace:'groundtrack'},async()=>{
      const source=readFileSync(fileURLToPath(new URL('src/settings-rules.js',root)),'utf8').replace(/^export /gm,'');
      // (As the phone's own script is: ES2015, small.)
      const {transform}=await import('esbuild');
      const {code}=await transform(source+'\nsettingsFor;chartOf;',{target:'es2015',minifyWhitespace:true,minifySyntax:true});
      return {contents:`export default ${JSON.stringify(code.replace(/settingsFor;chartOf;\s*$/,''))};`,loader:'js'};
    });
  }
};

mkdirSync(dirname(out),{recursive:true});
const result=await build({
  entryPoints:[fileURLToPath(new URL('native/pkjs/main.js',root))],
  // The SDK repackages this with webpack 1, whose parser takes ES2015 at most
  // and which indents every line of the file: a template literal spanning
  // lines would gain tabs, so none are emitted and every newline stays '\n'.
  bundle:true,format:'iife',platform:'browser',target:'es2015',supported:{'template-literal':false},minify:true,legalComments:'eof',
  banner:{js:'// Generated by tools/build-pkjs.mjs from native/pkjs/main.js. Do not edit.'},
  loader:{'.html':'text'},define:{GROUNDTRACK_FACE:JSON.stringify(face)},plugins:[data,pageAssets,rulesText],outfile:out,metafile:true,logLevel:'warning'
});
const bytes=Object.values(result.metafile.outputs)[0].bytes;
console.log(`${out}: ${(bytes/1024).toFixed(0)} KB`);
